# Generated by Django 3.2.5 on 2021-07-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customerbooking',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(help_text='vehicle model type', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(help_text='available number of seats for passangers'),
        ),
    ]
