# Generated by Django 3.2.5 on 2021-07-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210706_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerbooking',
            old_name='date',
            new_name='booked_on',
        ),
        migrations.AlterField(
            model_name='customerbooking',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
