# Generated by Django 3.2.5 on 2021-07-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210707_1143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerbooking',
            unique_together={('trip', 'customer')},
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
