# Generated by Django 3.2.5 on 2021-07-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210710_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='short_token',
            field=models.IntegerField(),
        ),
    ]
