# Generated by Django 3.2.5 on 2021-07-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_passwordresettoken_short_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='short_token',
            field=models.IntegerField(null=True),
        ),
    ]
