# Generated by Django 3.2.5 on 2021-07-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_passwordresettoken_short_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbooking',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
