# Generated by Django 3.2.5 on 2021-07-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customerbooking_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbooking',
            name='cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
