# Generated by Django 3.2.5 on 2021-07-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customerbooking_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbooking',
            name='cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customerbooking',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
