# Generated by Django 3.2.6 on 2021-08-05 16:46

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210731_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload),
        ),
        migrations.AlterField(
            model_name='driver',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 8, 5, 16, 46, 34, 316642)),
        ),
    ]
