# Generated by Django 3.2.6 on 2021-08-05 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_feedback_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
