# Generated by Django 3.2.6 on 2021-08-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_feedback_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='time',
            new_name='created_on',
        ),
    ]
