# Generated by Django 3.2.6 on 2021-08-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_time_feedback_created_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
